version: "3.3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "dh"
    ports:
      - "3306:3306"

  postgresql:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: "dh"
    ports:
      - "5432:5432"

